location_types:
  A:
    label: Городская промзона
    description: Участок внутри города или в непосредственной промышленной зоне.

  B:
    label: Пригородная индустриальная зона
    description: Участок в пределах 0–15 км от города, рядом с дорогой или коммуникациями.

  C:
    label: Периферийная производственная территория
    description: Участок в пределах 15–50 км от города.

  D:
    label: Малый промышленный населенный пункт
    description: Райцентр, моногород или поселок с производственной функцией.

  E:
    label: Изолированная территория
    description: Слабая логистика и низкая рыночная активность.
